config/routes.rb
Rails.application.routes.draw do
  resources :thoughts
  resources :tasks
  root to: 'homepage#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  enum priority: { high: "high", medium: "medium", low: "low" }
  # ensures a Task record cannot be created if its missing description and priority
  # validates_presence_of :description, :priority
  validates :description, presence: true
  validates :priority, presence: true
end

app/models/thought.rb
class Thought < ApplicationRecord
  # set optional: true so a thought can be created without a user
  belongs_to :user, optional: true
  has_one :user_category
  validates_presence_of :description

  enum priority: { 
    none:"none", 
    low: "low", 
    medium: "medium", 
    high: "high" 
  }, _prefix: true
# TODO: Refactor by Removing the none key value pair 
# Make sure if anyone does not choose any data from enum
# Application should Handle nil
  enum status: { 
    none: "none",
    todo: "todo",
    in_progress: "in_progress", 
    complete: "complete", 
    archived: "archived", 
    trash: "trash"
  }, _prefix: true

end

app/models/user_category.rb
class UserCategory < ApplicationRecord
  # belongs_to :user, :dependent => :destroy
  belongs_to :user, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def index
    @new_thought = Thought.new
    @thoughts = Thought.all
    @tasks = Task.all
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]


  def new
    @task = Task.new(priority: "medium")
    # handle creating a task from a thought
    if params[:thought_id]
      thought = Thought.find(params[:thought_id])
      @task.description = thought.description
    end
  end

  # GET /tasks/1
  def show
  end

  # GET /tasks/1/edit
  def edit
  end

  # create task from thought or /tasks/new
  def create
    # This makes the create task and destroy thought into 1 commit transaction so if either fails
    # the whole action of create and destroy doesn't leave data in a bad area.
    ActiveRecord::Base.transaction do
      @task = Task.new(task_params)
      if @task.save
        if params[:thought_id].present?
          thought = Thought.find(params[:thought_id])
          thought.destroy
          notice = 'Thought was deleted and a Task was successfully created.'
        else
          notice = 'Task was successfully created.'
        end
        redirect_to root_path, notice: notice
      else
        # ASK Lailson why does this not work with render?
        # render :new
        # NOTE: triggers when saving a thought fails.
        # # Test via setting if !@thought.save
        alert = 'Task failed to be saved.'
        redirect_to new_task_path, alert: alert
        # TODO: preserve description and priorioty when new page is rerendered
      end
    end
  end

  def update
    respond_to do |format|
      @task = Task.find(params[:id])
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to root_path, notice: 'Task was successfully destroyed.'
  end

  # TODO: fix indents
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def task_params
    params.require(:task).permit(:description, :priority)
  end
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
  before_action :set_thought, only: [:show, :edit, :update, :destroy]

  # GET /thoughts
  # GET /thoughts.json
  def index
    @thoughts = Thought.all    
  end

  # GET /thoughts/1
  # GET /thoughts/1.json
  # Delegating to find tasks id into private methods set_thought
  def show
  end

  # GET /thoughts/new
  def new
    @thought = Thought.new
    # handle creating a thought from a task
    if params[:task_id]
      task = Task.find(params[:task_id])
      @thought.description = task.description
    end
  end

  # GET /thoughts/1/edit
  def edit
  end

  # POST /thoughts
  # POST /thoughts.json
  def create
    # This makes the create task and destroy thought into 1 commit transaction so if either fails
    # the whole action of create and destroy doesn't leave data in a bad area.
    ActiveRecord::Base.transaction do
      @thought = Thought.new(thought_params)
      if @thought.save
        if params[:task_id].present?
          task = Task.find(params[:task_id])
          task.destroy
          notice = 'Task was deleted and a Thought was successfully created'
        else
          notice = 'Thought was successfully created.'
        end
        redirect_to root_path, notice: notice
      else
        # NOTE: triggers when saving a thought fails.
        # Test via setting if !@thought.save
        alert = 'Thought failed to be saved.'
        redirect_to new_thought_path, alert: alert
        # TODO: preserve description when new page is rerendered
      end
    end
  end

  # PATCH/PUT /thoughts/1
  # PATCH/PUT /thoughts/1.json
  def update
    respond_to do |format|
      if @thought.update(thought_params)
        format.html { redirect_to @thought, notice: 'Thought was successfully updated.' }
        format.json { render :show, status: :ok, location: @thought }
      else
        format.html { render :edit }
        format.json { render json: @thought.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thoughts/1
  # DELETE /thoughts/1.json
  def destroy
    @thought.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Thought was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # TODO: fix indents
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thought
      @thought = Thought.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def thought_params
      params.require(:thought).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/thoughts_helper.rb
module ThoughtsHelper
end

app/views/homepage/index.html.erb
<h1>Welcome to The Get Things Done App.</h1>

<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>


</br>
<%= form_with model: @new_thought do |form| %>
  <%= form.text_field :description %>
  <%= form.button "Create" %>
<% end %>

<table>
  <thead>
  <tr>
    <th>My Thoughts</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  </br>
  <tbody>
  <% @thoughts.each do |thought| %>
    <tr>
      <td><%= thought.description %></td>
      <td><%= link_to 'Show', thought %></td>
      <td><%= link_to 'Edit', edit_thought_path(thought) %></td>
      <td><%= link_to 'Destroy', thought, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <td><%= link_to 'Turn into a Task', new_task_path(thought_id: thought.id) %></td>
    </tr>
  <% end %>
  </tbody>
</table>


<table>
  <thead>
  <tr>
    <th>My Tasks</th>
    <th colspan="1">Priority</th>
  </tr>
  </thead>

  </br>
  <tbody>
  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.description %></td>
      <td><%= task.priority %></td>
      <td><%= link_to 'Edit', edit_task_path(task) %></td>
      <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <td><%= link_to 'Turn into a Thought', new_thought_path(task_id: task.id) %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GetThingsDoneApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.select :priority, %w[high medium low], include_blank: true %>
  </div>

  <div class="actions">
    <!-- pass thought id data so a thought can be deleted in POST call to create task -->
    <%= hidden_field_tag(:thought_id, params[:thought_id]) %>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Return to Homepage', root_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<p id="alert"><%= alert %></p>

<%= render 'form', task: @task %>

<%= link_to 'Back', root_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
  </br>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Return to Homepage', root_path %>

app/views/thoughts/_form.html.erb
<%= form_with(model: thought, local: true) do |form| %>
  <% if thought.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(thought.errors.count, "error") %> prohibited this thought from being saved:</h2>

      <ul>
        <% thought.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <!-- pass task id data so a task can be deleted in POST call to create thought -->
    <%= hidden_field_tag(:task_id, params[:task_id]) %>
    <%= form.submit %>
  </div>
<% end %>

app/views/thoughts/edit.html.erb
<h1>Editing Thought</h1>

<%= render 'form', thought: @thought %>

<%= link_to 'Show', @thought %> |
<%= link_to 'Return to Homepage', root_path %>

app/views/thoughts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Thoughts</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @thoughts.each do |thought| %>
      <tr>
        <td><%= thought.description %></td>
        <td><%= link_to 'Show', thought %></td>
        <td><%= link_to 'Edit', edit_thought_path(thought) %></td>
        <td><%= link_to 'Destroy', thought, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Return to Homepage', root_path %>

app/views/thoughts/new.html.erb
<h1>New Thought</h1>

<p id="alert"><%= alert %></p>

<%= render 'form', thought: @thought %>

<%= link_to 'Back', thoughts_path %>

app/views/thoughts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @thought.description %>
</p>

<%= link_to 'Edit', edit_thought_path(@thought) %> |
<%= link_to 'Return to Homepage', root_path %>